# cucumber.andon.yml
pipelines:
  Cucumber:
    #environment_variables:   
    group: Acceptance_testing
    materials:
      cucumber:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/jaheikki/cucumber-selenide-allure.git
        branch: master
        destination: cucumber-selenide-allure
        whitelist: # monitor changes only for this component
          - cucumber.andon.yml/**/*.*
    stages:
      - acceptance_tests: # name of stage
          jobs:
            run_acceptance_tests: # name of the job
              andon: # andon job configuration
                image: "andon.artifactorypro.shared.pub.tds.tieto.com/andon-gocd-agent-java8-maven3:v17.10.0" # elastic agent image
                #sonarqube: true
              artifacts:
               - test:
                   source: cucumber-selenide-allure/target/site/allure-maven-plugin/
               #- test:
               #    source: ci/hus-ci-tests/target/hustests.log
              tabs:
                Report: cucumber-selenide-allure/target/site/allure-maven-plugin/index.html 
              tasks:
               - exec: # Printout env variables
                   run_if: passed
                   command: bash
                   arguments:
                    - "-c"
                    - "cd cucumber-selenide-allure&&ls -ltr&&pwd&&mvn clean install allure:report -Dcucumber.options=\"--plugin io.qameta.allure.cucumberjvm.AllureCucumberJvm --tags @all\""
