# cucumber.andon.yml
pipelines:
  Cucumber:
    #environment_variables:   
    group: Acceptance_testing
    materials:
      cucumber:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/jaheikki/cucumber-selenide-allure.git
        branch: master
        destination: cucumber-selenide-allure
        whitelist: # monitor changes only for this component
          - cucumber.andon.yml/**/*.*
    stages:
      - acceptance_tests: # name of stage
          jobs:
            run_acceptance_tests: # name of the job
              andon: # andon job configuration
                image: "andon.artifactorypro.shared.pub.tds.tieto.com/andon-gocd-agent-java8-maven3:v17.10.0" # elastic agent image
                #sonarqube: true
#                ui_def_secure_variables:
#                  - TEST_PASSWORD
#                  - TEST_USER
                ui_def_variables:
                  - TEST_USER
#                selenium_grid:
#                  version: "2.53.1"
#                  browsers:
#                    - chrome
#                    - firefox
                deploy_env:
                  docker_compose:
                    - "cucumber-selenide-allure/src/test/resources/docker-compose.yml"
              artifacts:
               - test:
                   source: cucumber-selen ide-allure/target/site/allure-maven-plugin/
               #- test:
               #    source: ci/hus-ci-tests/target/hustests.log
              tabs:
                Report: cucumber-selenide-allure/target/site/allure-maven-plugin/index.html 
              tasks:
               - exec:
                   run_if: passed
                   command: bash
                   arguments:
                    - "-c"
                    - "pwd;ls -ltr;sleep 240s"
#                    - "cd cucumber-selenide-allure/src/test/resources && docker-compose -f docker-compose.yml up -d"
#               - exec: # Add chromedriver dependencies
#                   run_if: passed
#                   command: bash
#                   arguments:
#                    - "-c"
#                    - "sudo apt-get -y install libxi6 libgconf-2-4"
               - exec: # For debug
                   run_if: passed
                   command: bash
                   arguments:
                    - "-c"
                    - "cd cucumber-selenide-allure&&ls -ltr&&pwd&&mvn clean install -Dcucumber.options=\"--tags @order\" -Dselenide.browser=chrome -Dremote=http://hub:4444/wd/hub -Denv=remote"
#               - exec: # For debug
#                   run_if: passed
#                   command: bash
#                   arguments:
#                    - "-c"
##                    - "echo $BROWSERSTACK_USERNAME && echo $BROWSERSTACK_ACCESS_KEY"
#                    - "sleep 240s"
#               - exec:
#                   run_if: passed
#                   command: bash
#                   arguments:
#                    - "-c"
#                    #- "cd cucumber-selenide-allure&&ls -ltr&&pwd&&mvn clean install -Denv=remote -Dbrowser=chrome -Dcucumber.options=\"--plugin io.qameta.allure.cucumberjvm.AllureCucumberJvm --tags @all\""
#                    - "export BROWSERSTACK_USERNAME && export BROWSERSTACK_ACCESS_KEY && cd cucumber-selenide-allure&&ls -ltr&&pwd&&mvn clean install -Denv=remote -Dcucumber.options=\"--tags @order\" -Dbrowser=microservice.browser.Firefox53WindowsRemoteDriverProvider -Dlocal"
#               - exec: # Printout env variables
#                   run_if: passed
#                   command: bash
#                   arguments:
#                    - "-c"
#                    - "cd cucumber-selenide-allure&&ls -ltr&&pwd&&mvn allure:report"
